---

-  name: Install nagios on Ubuntu and CentOS
   become: true
   hosts: all
   tasks:

    -  name: Update local package index on Ubuntu
       ansible.builtin.apt:
          update_cache: yes
       when: ansible_distribution == "Ubuntu"

    -  name: Update local package index on CentOS
       ansible.builtin.dnf:
          update_cache: yes
       when: ansible_distribution == "CentOS"

    -  name: Install Nagios Core build toolchain web stack (Ubuntu)
       ansible.builtin.apt:
          name:
            - autoconf
            - gcc
            - lib6
            - make
            - wget
            - unzip
            - apache2
            - php
            - libapache2-mod-php
            - libgd-dev
            - ufw
          state: present
          update_cache: true
       when: ansible_distribution == "Ubuntu"

    -  name: Install Nagios Core build toolchain web stack (CentOS)
       ansible.builtin.dnf:
          name:
            - autoconf
            - gcc
            - glib
            - make
            - wget
            - unzip
            - httpd
            - php
            - gd-devel
            - firewalld
          state: present
          update_cache: true
       when: ansible_distribution == "CentOS"

    -  name: Install OpenSSL packages (Ubuntu)
       ansible.builtin.apt:
          name:
            - openssl
            - libssl-dev
          state: present
          update_cache: yes

    -  name: Install OpenSSL packages (CentOS)
       ansible.builtin.dnf:
          name:
            - openssl
            - openssl-devel
          state: present

    -  name: Get latest Nagios Core release details
       ansible.builtin.uri:
         url: https://api.github.com/repos/NagiosEnterprises/nagioscore/releases/latest
         return_content: true
         register: nagios_release

    -  name: Download Nagios Core tarball
       ansible.builtin.get_url:
         url: "{{ nagios_release.json.assets | map(attribute='browser_download_url') | select('search', '\\.tar\\.gz$') | first }}"
         dest: /tmp/nagioscore.tar.gz
         mode: '0644'

    -  name: Extract Nagios Core tarball
       ansible.builtin.unarchive:
         src: /tmp/nagioscore.tar.gz
         dest: /tmp/
         remote_src: true

# to be continued 
