---
- name: Install MySQL
  tags:
    - db
    - mysql
  ansible.builtin.apt:
    name: mysql-server
    state: latest
    update_cache: yes

- name: Start and enable MySQL
  tags:
    - db
    - mysql
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes
