# PREREQUISITE PACKAGES
- name: Install prerequisite packages (Ubuntu)
  apt:
    name: [apt-transport-https, curl, gnupg]
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install prerequisite packages (CentOS)
  yum:
    name: [curl, gnupg2]
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Add the Elastic GPG key (Ubuntu)
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
  args:
    creates: /usr/share/keyrings/elasticsearch-keyring.gpg
  when: ansible_facts['os_family'] == "Debian"

- name: Add the Elastic GPG key (CentOS)
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Add the Elastic 8.x APT repository (Ubuntu)
  copy:
    dest: /etc/apt/sources.list.d/elastic-8.x.list
    content: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main\n"
  when: ansible_facts['os_family'] == "Debian"

- name: Update apt cache after adding the repository
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Add the Elastic 8.x YUM repository (CentOS)
  yum_repository:
    name: elastic-8.x
    description: Elastic 8.x repository
    baseurl: https://artifacts.elastic.co/packages/8.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
  when: ansible_facts['os_family'] == "RedHat"


# INSTALL KIBANA
- name: Install Kibana (Ubuntu)
  apt:
    name: kibana
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install Kibana (CentOS)
  yum:
    name: kibana
    state: present
  when: ansible_facts['os_family'] == "RedHat"

